config/routes.rb
Rails.application.routes.draw do
  # Turn off registration  -> :skip => :registrations
  devise_for :users

  # Ref to /details page via tickets app
  #scope '/tickets' do
  #  get '/search', to: 'tickets#search'
  #end
  resources :tickets do
    get 'details', on: :member
    get 'search', on: :collection
  end

  get '/ads', :controller=>'ads', :action=>'index'
  get '/ads/:id', :controller=>'ads', :action=>'show'
  post '/ads', :controller=>'ads', :action=>'index'
  get '/reservations/', :controller=>'reservations', :action=>'index'
  get '/reservations/:id', :controller=>'reservations', :action=>'show'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  attr_reader :state, :city, :area_code, :time_zone
  before_action :set_ads, only: [:show]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /ads
  def index
    require 'savon'
    rvnumber = params[:rlogform].present? ? params[:rlogform][:rlogcode] : nil
    if rvnumber == nil
    @message = ""
    else
      wsdlurl = 'http://szop.pl.easypack24.net:8080/ReverseReturnWSService?wsdl'
      client = Savon.client(wsdl: wsdlurl,
                            log: true, # set true to switch on logging
                            log_level: :debug,
                            pretty_print_xml: true)
      giveitback = client.call(:get_report, message: {"code"=>rvnumber})
      testcode = giveitback.to_hash[:get_report_response][:return]
      trycode = testcode[:count]
      if trycode == '0'
             @result = "Mam niestety 0"
        else if trycode > '1'
             @result = "Jestem pusty :)"
           else
             data = giveitback.to_hash[:get_report_response][:return][:result][:target_address]
             @companyname = data[:company_name]
             @province = data[:province]
             @street = data[:street]
             @town = data[:town]
           end
        end
    end
  end

  # GET /ads/1
  def show

  end

  # GET /ads/search
  def search

  end

  # GET /ads/1/edit
  def edit

  end

  # POST /ads
  def create

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ad

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ad_params

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.

  # Metoda dostępna z każdego widoku generowanego przez kontorler dziedziczacy z ApplicationController
  helper_method :return_to

  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Authenticate users befor show content, scope: All
  before_action :authenticate_user!
  before_action :set_return_to, except: [:update, :create]

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource)
    '/tickets'
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  # Safe back method
  def return_to
    params[:return_to] || session[:return_to]
  end

  def set_return_to(path = nil)
    path ||= request.referer
    session[:return_to] = path
    if path.blank?
      session[:return_to] = '/tickets'
    else if path = 'users/sign_in'
           session[:return_to] = '/tickets'
         end
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

def show
		@reservation = Reservation.find(params[:id])
	end

def index
		@reservations = Reservation.all
	end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :details]
  before_action :authenticate_user!, except: [:show, :index, :details]

  # GET /tickets
  # GET /tickets.json
  def index
    @search = Ticket.search(params[:q])
    @tickets = @search.result.paginate(page: params[:page], per_page: 7)
    #@tickets = Ticket.all.paginate(page: params[:page], per_page: 7)
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/search
  def search

  end

  # GET /tickets/1/edit
  def edit
  end

  # GET /tickets/1/deta
  # # # GET /tickets.json/2
  def details

  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Nowy ticket został poprawnie utworzony.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Zgłoszenie zostało zaktualizowane.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket został usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:project_name, :ticket_no, :ticket_label, :deploy_date, :status, :email_address)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/ads/index.html.erb
<!-- Fourth section -->
<section class="section" id="contact">
  <div class="container">

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 text-center">
        <br />
        <%= form_for :rlogform, url: ads_path do |f| %>
            <div class="new-form">
              <%= f.label :rloglabel, "Wprowadź kod zwrotu", class: "new-formlabel" %><br>
              <%= f.text_field :rlogcode, class: "form-control" %>
            </div>
            <p>
            <div><%= f.submit :value => "Szukaj", class: "btn-search btn btn-primary btn-sm" %></div>
            </p>
        <% end %>
        <br />
      <div><b>FIRMA:</b></div><div><%= @companyname %></div>
      <br />
     <div><b>WOJEWÓDZTWO:</b></div><div><%= @province %></div>
      <br />
     <div><b>ULICA:</b></div><div><%= @street %></div>
      <br />
     <div><b>MIASTO:</b></div><div><%= @town %></div>
      <br />

    </div>
  </div>
</section>

app/views/ads/show.html.erb
<html>
<head>
<title><%= @ad.name %></title>
<body>
<p>
<b>Name:</b> <%= @ad.name %>
</p>
<p>
<b>Description:</b> <%= @ad.description %>
</p>
<p>
<b>Price:</b> <%= @ad.price %>
</p>
<p>
<b>Seller Id:</b> <%= @ad.seller_id %>
</p>
<p>
<b>Email:</b> <%= @ad.email %>
</p>
<p>
<img src="<%= @ad.img_url %>" />
</p>
</body>
</head>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport"    content="width=device-width, initial-scale=1.0">
<meta name="description" content="RubyOnRails Test">
<meta name="author"      content="Tomasz Nowak-Bańdura (syngress.pl)">
<title>Rezerwacje</title>
<link rel="shortcut icon" href="../images/gt_favicon.png">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body class="theme-invert">
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Support</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/tickets">Główna</a></li>
      <li><a href="/ads">Kod Zwrotu</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left">
      <div class="bs-component">
        <ul class="nav nav-pills">
          <li><a href="#">Szukaj <span class="badge"></span></a></li>
          <li><a href="#">Wiadomości <span class="badge">0</span></a></li>
        </ul>
        <div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div></div>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li>Logged in as <strong><%= current_user.email %></strong>.</li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Rejestracja", new_user_registration_path %></li>
          <li><%= link_to "Zaloguj", new_user_session_path  %></li>
      <% end %>
    </ul>
  </div>
</div>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
<!-- Load js libs only when the page is loaded. -->
<!-- Custom template scripts -->
</body>
</html>

app/views/reservations/index.html.erb
<html>
<br />
<body>
<div style="right: 0px; padding-right: 70px; margin-top: 50px; position:fixed;">
<a href="http://www.tickets.com/tickets#themes">Strona Poprzednia</a> - <a href="">Strona Główna</a>
</div>
  <div class="container">
  
    <h2 class="text-center title">Rezerwacje</h2>
    <p class="lead text-center">
    Tylko Pokoje Wolne - Tylko Pokoje Zarezerwowane - Wyświetl Wszystkie
      <br>
    </p>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-2">
        <div class="thumbnail">
          <%= link_to image_tag("rooms/A10.jpg") %>
          <div class="caption">
          <% @reservations.each do |reservation| %>
            <h3><a href="/reservations/<%= reservation.id %>"><%= reservation.rname %></a></h3>
            <p>
            <b>Status</b>: <%= reservation.rstatus %>
            <% end %> 
            <br />
            <b>Rezerwacja do dnia</b>: Brak rezerwacji
            <br />
            <b>Rodzaj pokoju</b>: Jednoosobowy
            <br />
            <b>Piętro</b>: I
            </p>
            <p><a href="#" class="btn btn-primary" role="button">Historia</a> <a href="#" class="btn btn-default" role="button">Rezerwuj</a></p>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <%= link_to image_tag("rooms/A10.jpg") %>
          <div class="caption">
            <h3>A11</h3>
            <p>
            <b>Status</b>: Wolny 
            <br />
            <b>Rezerwacja do dnia</b>: Brak rezerwacji
            <br />
            <b>Rodzaj pokoju</b>: Jednoosobowy
            <br />
            <b>Piętro</b>: I
            </p>
            <p><a href="#" class="btn btn-primary" role="button">Historia</a> <a href="#" class="btn btn-default" role="button">Rezerwuj</a></p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-sm-offset-2">
        <div class="thumbnail">
          <%= link_to image_tag("rooms/A10.jpg") %>
          <div class="caption">
            <h3>A12</h3>
            <p>
            <b>Status</b>: Wolny 
            <br />
            <b>Rezerwacja do dnia</b>: Brak rezerwacji
            <br />
            <b>Rodzaj pokoju</b>: Jednoosobowy
            <br />
            <b>Piętro</b>: II
            </p>
            <p><a href="#" class="btn btn-primary" role="button">Historia</a> <a href="#" class="btn btn-default" role="button">Rezerwuj</a></p>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <%= link_to image_tag("rooms/A10.jpg") %>
          <div class="caption">
            <h3>A13</h3>
            <p>
            <b>Status</b>: Wolny 
            <br />
            <b>Rezerwacja do dnia</b>: Brak rezerwacji
            <br />
            <b>Rodzaj pokoju</b>: Jednoosobowy
            <br />
            <b>Piętro</b>: III
            </p>
            <p><a href="#" class="btn btn-primary" role="button">Historia</a> <a href="#" class="btn btn-default" role="button">Rezerwuj</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/reservations/show.html.erb
<html>
<head>
<title><%= @reservation.rname %></title>
<body>
<p>
<b>Nazwa Pokoju:</b> <%= @reservation.rname %>
</p>
<p>
<b>Status Rezerwacji:</b> <%= @reservation.rstatus %>
</p>
<p>
<b>Czas:</b> <%= @reservation.rreservation %>
</p>
<p>
<b>Typ Pokoju:</b> <%= @reservation.rtype %>
</p>
<p>
<b>Piętro:</b> <%= @reservation.rfloor %>
</p>
<p>
<b>Cena:</b> <%= @reservation.rprice %>
</p>
<p>
<b>Historia Rezerwacji:</b> <%= @reservation.rhistory %>
</p>
<p>

</p>
</body>
</head>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket, html: { class: 'bootstrap-frm' }) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new-form">
    <%= f.label :Projekt, class: "new-formlabel" %>
    <%= f.select(:project_name, ['', 'Menadżer Paczek', 'API', 'SEH', 'Analiza', 'Allegro'], class: "form-control") %>
  </div>
  <div class="new-form">
    <%= f.label :Numer, class: "new-formlabel" %>
    <%= f.text_field :ticket_no, class: "form-control" %>
  </div>
  <div class="new-form">
    <%= f.label "Tytuł Zgłoszenia", class: "new-formlabel" %>
    <%= f.text_area :ticket_label, class: "form-control" %>
  </div>
  <div class="new-form">
    <%= f.label :Deploy, class: "new-formlabel" %>
    <%= f.text_field :deploy_date, class: "form-control" %>
  </div>
  <div class="new-form">
    <%= f.label :Status, class: "new-formlabel" %>
    <%= f.select(:status, ['', 'w kolejce', 'w trakcie', 'gotowe', 'wstrzymane'], class: "form-control") %>
  </div>
  <div class="new-form">
    <%= f.label :Kontakt, class: "new-formlabel" %>
    <%= f.text_field :email_address, class: "form-control" %>
  </div>
    <br />
  <div>
      <%= link_to 'Wracaj', tickets_path, class: "btn btn-primary" %>
      <%= f.submit :value => "Zapisz", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tickets/details.html.erb
<section class="section" id="themes" style="padding-top: 10px;">
  <div class="container">

    <h2 class="text-center title">Szczegóły zgłoszenia</h2>
    <p class="lead text-center"></p>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-2">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= @ticket.ticket_label %></h3>
            <br />
            <p>
              <%#params[:id] %>
              <%#@ticket.inspect %>
              <b>Numer zgłoszenia:</b> <a href="https://jira.inpost.pl/browse/<%= @ticket.ticket_no %>" target="_blank"><%= @ticket.ticket_no %></a>
              <br />
              <b>Projekt</b>: <%= @ticket.project_name %>
              <br />
              <b>Deploy</b>: <%= @ticket.deploy_date %>
              <br />
              <b>Status</b>:
              <% if @ticket.status == "gotowe" %>
              <span class="label label-success"><%= @ticket.status %></span>
              <% else if @ticket.status == "w trakcie"  %>
              <span class="label label-warning"><%= @ticket.status %></span>
              <% else if @ticket.status == "w kolejce"  %>
              <span class="label label-info"><%= @ticket.status %></span>
              <% end  %>
              <% end  %>
              <% end  %>
              <br /><br />
              <b>Opis</b>:
              <br />
              <pre>Należy wprowadzić filtrowanie domen, których SZOP nie obsłuży, wyświetlając klientowi odpowiedni komunikat. W chwili obecnej MP wyrzuca komunikat o błędzie.</pre>
            </p>
            <br />
            <% if user_signed_in? %>
                <p><%= link_to 'Wracaj', return_to, class: "btn btn-primary btn-sm"  %> <a href="/reservations" class="btn btn-primary btn-sm" role="button">Edytuj opis</a></p>
            <% else if !user_signed_in? %>
                    <p><%= link_to 'Wracaj', return_to, class: "btn btn-primary btn-sm"  %></p>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>
<!-- Fourth (Contact) section -->
<section class="section" id="contact">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 text-center">
        <p>Wszystkie dodatkowe pytania dot. przesyłanych zgłoszeń, kieruj pod adres:</p>
        <p><b>support@paczkomaty.pl</b><br><br></p>
      </div>
    </div>
  </div>
</section>

app/views/tickets/edit.html.erb
<div style="text-align: center;">
<h1>Edycja zgłoszenia</h1>

<%= render 'form' %>
  <br />
<%= link_to 'Podgląd', @ticket %>

    </div>

app/views/tickets/hello.html.erb
<html>
<body>
<h1><%= @message %></h1>
</body>
</html>

app/views/tickets/index.html.erb
<!-- Main (Home) section -->
<section class="section" id="head">
  <div class="container">

    <div class="row">
      <div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center"> 

        <!-- Content -->
        <h3 class="tagline">
          <h1>Przekazane Zgłoszenia</h1>
          <br />
<table>
  <thead>
    <tr>
      <th class="center-userslist">Projekt</th>
      <th class="center-userslist">Numer</th>
      <th class="center-userslist">Tytuł Zgłoszenia</th>
      <th class="center-userslist">Deploy</th>
      <th class="center-userslist">Status</th>
      <th class="center-userslist">Kontakt:</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <br />
<br />
  <tbody>
    <% @tickets .order("created_at desc").each do |ticket| %>
      <tr>
        <td class="center-userslist"><%= ticket.project_name %></td>
        <td class="center-userslist"><a href="https://jira.inpost.pl/browse/<%= ticket.ticket_no %>" target="_blank"><%= ticket.ticket_no %></a></td>
        <td class="center-userslist"><%= truncate(ticket.ticket_label, length: 67) %></td>
        <td class="center-userslist"><%= ticket.deploy_date %></td>
        <td class="center-userslist"><%= ticket.status %></td>
        <td class="center-userslist email-userlist"><a href="mailto:<%= ticket.email_address %>"><%= ticket.email_address %></a></td>
        <!-- <td><%= link_to image_tag("../images/show.png"), ticket, class: "img-userlist"  %></td> -->
        <!-- <td><%= link_to 'Show', ticket %></td> -->
        <td><%= link_to image_tag("details.png"), details_ticket_path(ticket), class: "img-userlist" %></td>
        <td><%= link_to image_tag("../images/edit.png"), edit_ticket_path(ticket), class: "img-userlist" %></td>
        <td><%= link_to image_tag("delete.png"), ticket, class: "img-userlist", method: :delete, data: { confirm: 'Wykasować ticket z bazy danych ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    <div class="pagination">
    <%= will_paginate @tickets, :class => 'page' %>
    </div>
      </h3>
        <br />
        <% if user_signed_in? %>
        <p>
        <%= link_to 'Dodaj nowy Ticket', new_ticket_path, class: "btn btn-primary" %>
        </p>
        <% else if !user_signed_in? %>
        <% end %>
            <% end %>
        </div> <!-- /col -->
    </div> <!-- /row -->
  </div>
</section>

<!-- Fourth section -->
<section class="section" id="contact">
  <div class="container">

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 text-center">
        <br />
        <%= search_form_for @search do |f| %>
            <div class="new-form">
              <%= f.label :project_name, "Szukaj", class: "new-formlabel" %>
              <%= f.search_field :project_name_or_ticket_no_or_status_cont, class: "form-control" %>
            </div>
            <div><%= f.submit :value => "Szukaj", class: "btn-search btn btn-primary btn-sm" %></div>

        <br />
        <p class="lead">lub sortuj wynik po wybranym projekcie</p>
        <ul class="list-inline list-social">
           <li><%= f.radio_button :project_name_eq, 'Menadżer Paczek', checked: false, :onclick => "this.form.submit();" %> MP</li>
           <li><%= f.radio_button :project_name_eq, 'SEH', checked: false, :onclick => "this.form.submit();" %> SEH</li>
           <li><%= f.radio_button :project_name_eq, 'API', checked: false, :onclick => "this.form.submit();" %> API</li>
           <li><%= f.radio_button :project_name_eq, 'Allegro', checked: false, :onclick => "this.form.submit();" %> Allegro</li>
        </ul>
        <% end %>
      </div>

    </div>

  </div>
</section>

app/views/tickets/new.html.erb
<section class="section" id="head">
  <div class="container">

    <div class="row">
      <div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">
        <!-- App Content -->

        <div>

          <h1>Utwórz nowy ticket</h1><br />

          <%= render 'form' %>

        </div>
    <br />
      </div> <!-- /col -->
    </div> <!-- /row -->
  </div>
</section>

app/views/tickets/search.html.erb
<!-- Main (Home) section -->
<section class="section" id="head">
  <div class="container">

    <div class="row">
      <div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">

        <!-- Content -->
        <h3 class="tagline">
          <h1>Wyszukiwarka</h1>
          <br />
          <table>
            <tbody>
                TEST TEST TEST
            </tbody>
          </table>
          <div class="pagination">

          </div>
        </h3>
        <br />

      </div> <!-- /col -->
    </div> <!-- /row -->
  </div>
</section>

<!-- Fourth section -->
<section class="section" id="contact">
  <div class="container">

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2 text-center">
        <br />
        <p class="lead">Sortuj wynik po wybranym projekcie</p>
        <ul class="list-inline list-social">

          <li><%= check_box("post", "validated") %> MP</li>
          <li><%= check_box("post", "validated") %> API</li>
          <li><%= check_box("post", "validated") %> SEH</li>
          <li><%= check_box("post", "validated") %> ALLEGRO</li>
        </ul>
      </div>
    </div>

  </div>
</section>

app/views/tickets/show.html.erb
<div style="text-align: center;">

  <h1>Zweryfikuj zapisane informacje:</h1><br />

  <div class="panel panel-default panel-width">
    <div class="panel-heading">
      <h3 class="panel-title">Projekt:</h3>
    </div>
    <div class="panel-body">
      <div><%= @ticket.project_name %></div>
    </div>
  </div>

  <div class="panel panel-default panel-width">
    <div class="panel-heading">
      <h3 class="panel-title">Numer:</h3>
    </div>
    <div class="panel-body">
      <div><%= @ticket.ticket_no %></div>
    </div>
  </div>

  <div class="panel panel-default panel-width">
    <div class="panel-heading">
      <h3 class="panel-title">Tytuł Zgłoszenia:</h3>
    </div>
    <div class="panel-body">
      <div><%= @ticket.ticket_label %></div>
    </div>
  </div>

  <div class="panel panel-default panel-width">
    <div class="panel-heading">
      <h3 class="panel-title">Deploy:</h3>
    </div>
    <div class="panel-body">
      <div><%= @ticket.deploy_date %></div>
    </div>
  </div>

  <div class="panel panel-default panel-width">
    <div class="panel-heading">
      <h3 class="panel-title">Status:</h3>
    </div>
    <div class="panel-body">
      <div><%= @ticket.status %></div>
    </div>
  </div>

  <div class="panel panel-default panel-width">
    <div class="panel-heading">
      <h3 class="panel-title">E-mail:</h3>
    </div>
    <div class="panel-body">
      <div><%= @ticket.email_address %></div>
    </div>
  </div>

<b>
<%= link_to 'Edytuj Ticket', edit_ticket_path(@ticket), class: "btn btn-primary" %>
<%= link_to 'Strona Główna', tickets_path, class: "btn btn-primary" %>
</b>
<br /><br />
</div>